<!DOCTYPE html>
<html lang="cs-CZ">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Cache-Control" content="no-cache, must-revalidate"/>
	<title><?= parse_url($_SERVER['HTTP_HOST'], PHP_URL_PORT) ? parse_url($_SERVER['HTTP_HOST'], PHP_URL_HOST) : $_SERVER['HTTP_HOST'] ?> | LogViewer <?= $version ?> </title>
	<link rel="shortcut icon" href="favicon.ico"/>
	<meta name="robots" content="noarchive"/>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
	<link rel="stylesheet" type="text/css" href="css/core.css"/>
	<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
	<script src="js/bootstrap.min.js" type="text/javascript"></script>
	<script src="js/core.js" type="text/javascript"></script>
</head>
<body class="<?= $config->header ? 'withHeaders' : ''?>">
<?=$content;?>
</body>
</html>