<div id="filters" class="floating">
	<form action="index.php" method="get" class="form-inline">

		<? if ($action == 'show') { ?>
		<a href="<?= $listUrl ?>" class="btn btn-danger" style="float: left"><i class="icon-chevron-left icon-white"></i> Return back</a>
		<? } ?>

		<?foreach ($items as $name => $value) { if ($name === 'raw') continue; ?>
		<? if (is_bool($value)) { ?>
			<label for="<?= $name ?>" class="checkbox">
				<input type="checkbox" id="<?= $name ?>" name="<?= $name ?>"
					<?= $value ? 'checked="checked"' : null; ?> value="1"/>
				<?= ucfirst($name) ?>
			</label>
			<? } else { ?>
			<label for="<?= $name ?>"><?= ucfirst($name)?></label>
			<input type="text" name="<?= $name ?>" value="<?= htmlspecialchars($value) ?>" id="<?= $name ?>"
			       class="input-small"/>
			<? } ?>
		<? } ?>
		<input type="submit" value="Apply" class="btn btn-primary"/>

		<? if ($action == 'show') { ?>
		<a href="<?= $rawUrl ?>" class="btn btn-success"><i class="icon-arrow-down icon-white"></i>Download</a>
		<? } ?>

		<?php
		if (preg_match('/exception-[\-0-9]*-[[:alnum:]]*\.html$/i', $log)) {
			echo '<a href="' . $listUrl . '&action=resolved&log=' . $log . '" class="btn btn-danger"><i class="icon-ok icon-white"></i> Resolved</a>'; // delete resolved exception bluescreen
		}
		?>
		<input type="hidden" name="action" value="<?=$action?>"/>
		<input type="hidden" name="log" value="<?=$log?>"/>
	</form>
</div>