<?= $filters ?>

<div class="logs">

	<?= isset($_GET['message']) ? '<p class="alert"><strong>' . htmlentities($_GET['message']) . '</strong></p>' : null; ?>

	<?foreach ($logs as $group => $logs) { ?>

	<div class="logGroup">
		<h4><?=$group?></h4>
		<ul class="autoscroll">

			<?if (count($logs) > 0): ?>
			<? foreach ($logs as $log): ?>
				<li>
					<a href="<?=$showUrl?>&amp;log=<?=$log['path']?>&amp;action=show"
					   title="<?=$log['path']?>"><?=$log['file']?></a>
					<span>(<?=$log['size']?>)</span>
				</li>
				<? endforeach; ?>
			<? endif;?>
		</ul>
	</div>
	<? } ?>

	<div class="cleaner"></div>
</div>