<? /** @var \logviewer\Config $config */ ?>
<? if ($config->header) { ?><?= $filters ?><div class="show"><h3>Output - <?=$log?></h3><? } ?>

	<div class="output" id="top">
		<?
		switch ($logType) {

			case 'html':
				echo '<iframe src="data:text/html;base64, ' . base64_encode($output) . '"></iframe>';
				break;

			case 'jpg':
			case 'jpeg':
				echo '<div class="printscreen"><img src="data:image/jpeg;charset=utf-8;base64, ' . base64_encode($output) . '" alt="' .$log .'"/></div>';
				break;
			case 'png':
				echo '<div class="printscreen"><img src="data:image/png;charset=utf-8;base64, ' . base64_encode($output) . '" alt="' .$log .'"/></div>';
				break;

			case 'txt':
			case 'log':
			default:
			if (is_array($output)) {
				$i = 1;
				echo '<ul class="nav nav-tabs" id="servers">';
				foreach (array_keys($output) as $server) {
					echo '<li class="'. (($i == 1) ? ' active' : null )  .'"><a href="#server-' . $i. '" data-toggle="tab" title="' . $server . '">&nbsp;' . $i . '&nbsp;</a></li>';
					$i++;
				}
				echo '</ul>';

				echo '<div class="tab-content">';
				$i = 1;
				foreach ($output as $server => $data) {
					echo '<div class="tab-pane'. (($i === 1) ? ' active' : null )  .'" id="server-' . $i . '">
					<h4>' . $server . '</h4>';
					echo '<pre>' . preg_replace(array_keys($config->_replace), array_values($config->_replace), htmlspecialchars($data, ENT_QUOTES)) . '</pre>';
					echo '</div>';
					$i++;
				}
				echo '</div>';

			} else {
				// lokalni log prozenu nejdriv obarvovacem a pak nahradim systemove promenne v druhem kole
				$output = htmlspecialchars($output, ENT_QUOTES | ENT_SUBSTITUTE);
				$output = preg_replace(array_keys($config->_replace), array_values($config->_replace), $output);
				$replace = array(
					'/\{dirname\}/i' => dirname($log),
					'/\{url\}/i' => $url,
				);
				$output = preg_replace(array_keys($replace), array_values($replace), $output);
				echo '<pre>' . $output . '</pre>';
			}
				break;
		}
		?>
	</div>
<? if ($config->header) { ?></div><? } ?>