<?
/**
 * @var \logviewer\View $this
 * @var string $format
 * @var int $lines
 * @var string $read
 * @var string $type
 * @var string $direction
 * @var string $get
 */
?>
<div class="navbar navbar-fixed-top">

	<a class="navbar-brand" href="<?= $this->url() ?>"
	   title="Server: <?= \logviewer\Utils::getServerName() ?>">LogViewer</a>

	<? if ($format) { ?>
		<a class="btn btn-default navbar-btn btn-danger"
		   href="<?= $this->url(array_merge($params, ['format' => null])) ?>">
			&laquo; Back
		</a>
	<? } ?>

	<!-- Lines -->
	<a href="<?= $this->url(array_merge($params, ['lines' => 150]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 150) ? 'disabled' : null ?>">150</a>

	<a href="<?= $this->url(array_merge($params, ['lines' => 500]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 500) ? 'disabled' : null ?>">500</a>

	<a href="<?= $this->url(array_merge($params, ['lines' => 1000]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 1000) ? 'disabled' : null ?>">1000</a>

	<!-- Read -->
	<? $read = ($read === 'tail') ? 'head' : 'tail'; ?>
	<a href="<?= $this->url(array_merge($params, ['read' => $read]), $get) ?>" class="btn btn-default navbar-btn">
		Read log <?= $params['read'] ? : 'tail' ?>
	</a>

	<!-- Read servers -->
	<? $type = ($type === 'single') ? 'multi' : 'single'; ?>
	<a href="<?= $this->url(array_merge($params, ['type' => $type]), $get) ?>" class="btn btn-default navbar-btn">
		Read from <?= $params['type'] ? : 'single' ?> server
	</a>

	<!-- Direction -->
	<? $direction = ($direction === 'normal') ? 'reverse' : 'normal'; ?>
	<a href="<?= $this->url(array_merge($params, ['direction' => $direction]), $get) ?>"
	   class="btn btn-default navbar-btn">
		<?= ucfirst($params['direction'] ? : 'normal') ?> lines order
	</a>

	<!-- Download -->
	<? if ($format) { ?>
		<a class="btn btn-default navbar-btn btn-success"
		   href="<?= $this->url(array_merge($params, ['format' => 'raw']), $get) ?>">
			Download
		</a>
	<? } ?>

</div>