<?
/**
 * @var \logviewer\View $this
 * @var string $format
 * @var int $lines
 * @var string $read
 * @var string $type
 * @var string $direction
 * @var string $get
 */
?>
<div class="navbar navbar-default navbar-fixed-top">

	<a class="navbar-brand" href="<?= $this->url() ?>"
	   title="Server: <?= \logviewer\Utils::getServerName() ?>">LogViewer</a>

	<? if ($format) { ?>
		<a class="btn btn-default navbar-btn btn-danger"
		   href="<?= $this->url(array_merge($params, ['format' => null])) ?>">
			&laquo; Back
		</a>
	<? } ?>

	<a class="btn btn-default navbar-btn btn-primary" href="<?= $this->url($params, $get); ?>">
		Reload
	</a>

	<!-- Lines -->
	<a href="<?= $this->url(array_merge($params, ['lines' => 150]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 150) ? 'disabled' : null ?>">150</a>

	<a href="<?= $this->url(array_merge($params, ['lines' => 500]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 500) ? 'disabled' : null ?>">500</a>

	<a href="<?= $this->url(array_merge($params, ['lines' => 1000]), $get) ?>"
	   class="btn btn-default navbar-btn <?= ($lines == 1000) ? 'disabled' : null ?>">1000</a>

	<!-- Read -->
	<? $read = ($read === 'tail') ? 'head' : 'tail'; ?>
	<div class="btn-group navbar-btn">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			Read <?= $params['read'] ? : 'tail' ?>
			<span class="caret"></span>
		</button>

		<ul class="dropdown-menu" role="menu">
			<li><a href="<?= $this->url(array_merge($params, ['read' => 'tail']), $get) ?>">Read tail</a></li>
			<li><a href="<?= $this->url(array_merge($params, ['read' => 'head']), $get) ?>">Read head</a></li>
		</ul>
	</div>

	<!-- Read servers -->
	<? $type = ($type === 'single') ? 'multi' : 'single'; ?>
	<div class="btn-group navbar-btn">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			<?= ucfirst($params['type'] ? : 'single') ?> server
			<span class="caret"></span>
		</button>

		<ul class="dropdown-menu" role="menu">
			<li><a href="<?= $this->url(array_merge($params, ['type' => 'single']), $get) ?>">Single server</a></li>
			<li><a href="<?= $this->url(array_merge($params, ['type' => 'multi']), $get) ?>">Multi server</a></li>
		</ul>
	</div>

	<!-- Direction -->
	<? $direction = ($direction === 'normal') ? 'reverse' : 'normal'; ?>
	<div class="btn-group navbar-btn">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			<?= ucfirst($params['direction'] ? : 'normal') ?> line order
			<span class="caret"></span>
		</button>

		<ul class="dropdown-menu" role="menu">
			<li><a href="<?= $this->url(array_merge($params, ['direction' => 'normal']), $get) ?>">Normal line order</a></li>
			<li><a href="<?= $this->url(array_merge($params, ['direction' => 'reverse']), $get) ?>">Reverse line order</a>
			</li>
		</ul>
	</div>

	<!-- Download -->
	<? if ($format) { ?>
		<a class="btn btn-default navbar-btn btn-success"
		   href="<?= $this->url(array_merge($params, ['format' => 'raw']), $get) ?>">
			Download
		</a>
	<? } ?>

</div>