<? /** @var \logviewer\View $this */ ?>
<!DOCTYPE html>
<html lang="cs-CZ">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Cache-Control" content="no-cache, must-revalidate"/>
	<title><?= \logviewer\Utils::getServerName() ?> | LogViewer </title>
	<link rel="shortcut icon" href="<?= $this->url('favicon.ico') ?>"/>
	<meta name="robots" content="noarchive"/>
	<link rel="stylesheet" type="text/css" href="<?= $this->url('css/bootstrap.min.css') ?>"/>

	<link rel="stylesheet" type="text/css" href="<?= $this->url('css/core.css') ?>"/>
	<script src="<?= $this->url('js/jquery.min.js') ?>"></script>
	<script src="<?= $this->url('js/bootstrap.min.js') ?>"></script>
</head>
<body>