<? /** @var \logviewer\View $this */ ?>
<? $this->getHeader() ?>

<? $this->getFilters(); ?>

	<div class="logs">

		<?=
		isset($_GET['message']) ? '<p class="alert"><strong>' . htmlentities(
				$_GET['message']
			) . '</strong></p>' : null; ?>

		<? foreach ($logs as $group => $logs) { ?>

			<div class="panel panel-default">
				<div class="panel-heading" title="<?= realpath($group) ?>">
					<?= \logviewer\Utils::highlights(realpath($group), \logviewer\Config::highlights()) ?>
					<span class="badge pull-right"><?= count($logs) ?></span>
				</div>
				<? if (count($logs) > 0) { ?>
					<ul>

						<? foreach ($logs as $log) { ?>
							<li>
								<a href="<?= $this->url(array_merge($params, ['format' => 'view']), ['log' => $log['path']]); ?>"
								   title="<?= realpath($log['path']) ?>"><?= $log['file'] ?></a>
								<small>(<?= $log['size'] ?>)</small>
							</li>
						<? } ?>
					</ul>
				<? } ?>

				<div class="panel-footer"><?= realpath($group) ?></div>
			</div>

		<? } ?>
	</div>

<? $this->getFooter() ?>