<? /** @var \logviewer\View $this */ ?>
<? /** @var \logviewer\LogProcessor $logProcessor */ ?>

<? $this->getHeader() ?>

<? $this->getFilters(); ?>

<?
$escapeAndReplace = function ($output, $url) use ($log, $logProcessor) {
	$output = $logProcessor->highlight($output);
	return $logProcessor->replaceKeywords($output, $url, dirname($log));
};
?>

<div class="show"><h3><?= realpath($log) ?></h3>

	<div class="output" id="top">
		<?
		switch ($logType) {

			case 'html':
				echo '<iframe src="data:text/html;base64, ' . base64_encode($output) . '"></iframe>';
				break;

			case 'jpg':
			case 'jpeg':
				echo '<div class="printscreen"><img src="data:image/jpeg;charset=utf-8;base64, ' . base64_encode(
						$output
					) . '" alt="' . $log . '"/></div>';
				break;
			case 'png':
				echo '<div class="printscreen"><img src="data:image/png;charset=utf-8;base64, ' . base64_encode(
						$output
					) . '" alt="' . $log . '"/></div>';
				break;

			case 'txt':
			case 'log':
			default:
				if (is_array($output)) {
					echo '<ul class="nav nav-tabs" id="servers">';
					foreach ($output as $i => $server) {
						echo '<li class="' . (($i == 0) ? ' active' : null) . '"><a href="#server-' . ($i + 1) . '" data-toggle="tab" title="' . $server['host'] . '">&nbsp;' . ($i + 1) . '&nbsp;</a></li>';
					}
					echo '</ul>';
					echo '<div class="tab-content">';
					foreach ($output as $i => $server) {
						echo '<div class="tab-pane' . (($i === 0) ? ' active' : null) . '" id="server-' . ($i + 1) . '">';
						echo '<h4><a href="' . $server['url'] . '">' . $server['host'] . '</a></h4>';
						echo '<pre>' . $escapeAndReplace($server['output'], $server['url']) . '</pre>';
						echo '</div>';
					}
					echo '</div>';

				} else {
					// lokalni log prozenu nejdriv obarvovacem a pak nahradim systemove promenne v druhem kole
					echo '<pre>' . $escapeAndReplace($output, $url) . '</pre>';
				}
				break;
		}
		?>
	</div>
	<? $this->getFooter(); ?>
